daemon:
  name: Lucy
  gender: M
  hp: [50, 100]
  strength: [30, 100]
  speed: [36, 100]
  side: light
  category: player
wizard:
  name: Jandalk
  gender: M
  hp: [60, 100]
  strength: [10, 100]
  speed: [8, 100]
  side: light
  category: player
knight:
  name: Mrs Coward
  gender: F
  hp: [50, 100]
  strength: [20, 100]
  speed: [12, 100]
  side: dark
  category: player
spider_m:
  name: Jaragon
  gender: M
  hp: [12, 100]
  strength: [9, 100]
  speed: [18, 100]
  side: dark
  category: mob
spider_f:
  name: Jiramob
  gender: F
  hp: [12, 100]
  strength: [9, 100]
  speed: [18, 100]
  side: dark
  category: mob
snake_m:
  name: Sertle
  gender: M
  hp: [15, 100]
  strength: [12, 100]
  speed: [16, 100]
  side: dark
  category: mob
snake_f:
  name: Zeaka
  gender: F
  hp: [15, 100]
  strength: [12, 100]
  speed: [16, 100]
  side: dark
  category: mob
phoenix:
  name: Conny
  gender: M
  hp: [80, 100]
  strength: [70, 100]
  speed: [60, 100]
  side: light
  category: legendary
basilisk:
  name: Kaa
  gender: M
  hp: [80, 100]
  strength: [80, 100]
  speed: [30, 100]
  side: dark
  category: legendary
griffon:
  name: Albert
  gender: M
  hp: [80, 100]
  strength: [70, 100]
  speed: [90, 100]
  side: light
  category: legendary
dragon:
  name: Blargy
  gender: M
  hp: [70, 100]
  strength: [90, 100]
  speed: [60, 100]
  side: dark
  category: legendary
