warrior:
  hp: [50, 10]
  strength: [12, 3]
  speed: [11, 2]
  category: player
mage:
  hp: [30, 6]
  mp: [10, 4]
  strength: [10, 3]
  speed: [10, 2]
  category: player
thief:
  hp: [35, 7]
  strength: [7, 2]
  speed: [19, 4]
  category: player
rat:
  hp: [15, 5]
  strength: [5, 2]
  speed: [16, 2]
  category: common
wolf:
  hp: [25, 5]
  strength: [8, 2]
  speed: [12, 2]
  category: common
snake:
  hp: [23, 7]
  strength: [7, 2]
  speed: [6, 2]
  inflicts: [poison, 5]
  category: common
slime:
  hp: [80, 4]
  strength: [3, 2]
  speed: [4, 2]
  inflicts: [poison, 10]
  category: common
spider:
  hp: [16, 5]
  strength: [9, 2]
  speed: [12, 2]
  inflicts: [poison, 20]
  category: common
zombie:
  hp: [80, 5]
  strength: [8, 2]
  speed: [6, 2]
  category: rare
orc:
  hp: [60, 5]
  strength: [13, 2]
  speed: [12, 2]
  category: rare
skeleton:
  hp: [45, 5]
  strength: [10, 2]
  speed: [10, 2]
  category: rare
demon:
  hp: [70, 5]
  strength: [10, 2]
  speed: [18, 2]
  inflicts: [burn, 10]
  category: rare
vampire:
  hp: [70, 5]
  strength: [13, 2]
  speed: [10, 2]
  category: rare
dragon:
  hp: [110, 5]
  strength: [25, 2]
  speed: [8, 2]
  inflicts: [burn, 2]
  category: rare
golem:
  hp: [70, 5]
  strength: [45, 2]
  speed: [2, 1]
  category: rare
sorcerer:
  hp: [45, 5]
  mp: [13, 1]
  strength: [10, 2]
  speed: [8, 2]
  inflicts: [burn, 5]
  category: rare
chimera:
  hp: [250, 2]
  strength: [90, 2]
  speed: [16, 2]
  inflicts: [poison, 3]
  category: legendary
basilisk:
  hp: [180, 3]
  strength: [100, 2]
  speed: [18, 2]
  inflicts: [poison, 2]
  category: legendary
minotaur:
  hp: [120, 3]
  strength: [60, 2]
  speed: [40, 2]
  category: legendary
balrog:
  hp: [270, 3]
  strength: [200, 2]
  speed: [14, 2]
  inflicts: [burn, 3]
  category: legendary
phoenix:
  hp: [500, 3]
  strength: [180, 2]
  speed: [28, 2]
  inflicts: [burn, 3]
  category: legendary
