daemon:
  name: Lucy
  hp: [40, 100]
  strength: [50, 100]
  speed: [50, 100]
  side: light
  category: player
wizard:
  name: Jandalk
  hp: [60, 100]
  mp: [10, 100]
  strength: [7, 100]
  speed: [3, 100]
  side: light
  category: player
knight:
  name: Mr Coward
  hp: [50, 100]
  strength: [50, 100]
  speed: [50, 2]
  side: dark
  category: player
